local ALLOWED_LUA = {
	-- gm_excess_island_night
	["f3a9e5157f25d221d2b3387f55cc22c6"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_309')[1];local door=ents.FindByName('i3_sp_door5')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["8f830f5939d09b7cfee4851d4132e571"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_308')[1];local door=ents.FindByName('i3_sp_door4')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["377582bb92686b70a4a7377b1de6f3a3"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_b11a')[1];local tr1=ents.FindByName('b11_shutter1')[1];local tr2=ents.FindByName('b11_shutter2')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Toggle Shutter 1','Toggle Shutter 2'});function controlbox:TriggerInput(iname,value) if(iname=='Toggle Shutter 1') then if (value>0) then tr1:Fire('Toggle','',0) end else if (value>0) then tr2:Fire('Toggle','',0) end end end end
	["e6073b3b67df761aba65074226bab173"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_b11d')[1];local door=ents.FindByName('b11_celldoor3')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door 3 - Control','Door 3 - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door 3 - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["c18fdfcdbfb678350b2051f009ad2a16"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_b11e')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Physics Toggle','Weapon Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Physics Toggle') and (value>0) and not self.LightEdge then ents.FindByName('b11_physics')[1]:Fire('Toggle','',0) else if (value>0) and not self.LightEdge then ents.FindByName('b11_wepstrip')[1]:Fire('Toggle','',0) end end self.LightEdge=value>0 end end
	["42aa5a2b7591fb638b2fcfcb37576863"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_b11b')[1];local door=ents.FindByName('b11_celldoor2')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door 2 - Control','Door 2 - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door 2 - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["256507181f03abc65f1345fbcc34b3c7"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_b11c')[1];local door=ents.FindByName('b11_celldoor1')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door 1 - Control','Door 1 - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door 1 - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["873f7d587c3293aa2f93365f9fddb8ed"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_304')[1];local door=ents.FindByName('i3_garage4_door')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["8ffa1646c8c427faecfaf353337c7618"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_301')[1];local door=ents.FindByName('i3_garage1_door')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["7968b1850ee7892d5dc52b6939a364fa"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_302')[1];local door=ents.FindByName('i3_garage2_door')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["7da014290063534942cfb9ad31fae513"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_101')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door Lock'});function controlbox:TriggerInput(iname,value) if(iname=='Door Lock') then local door=ents.FindByName('ug_lg_door')[1] if(value>0) then door:Fire('Lock','',0) else door:Fire('Unlock','',0) end end self.LightEdge=value>0 end end
	["8eb4db77605aa51d562828f2b7f24736"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_305')[1];local dr1=ents.FindByName('i3_maint_door01')[1];local dr2=ents.FindByName('i3_maint_door02')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door 1 - Lock','Door 2 - Lock'});function controlbox:TriggerInput(iname,value) if(iname=='Door 1 - Lock') then door=dr1 else door=dr2 end if(value>0) then door:Fire('Lock','',0) else door:Fire('Unlock','',0) end self.LightEdge=value>0 end end
	["561c2762ab141eb25d13cd9c02a014d4"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_106')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door Lock'});function controlbox:TriggerInput(iname,value) if(iname=='Door Lock') then local door=ents.FindByName('i1_backmaint_door')[1] if(value>0) then door:Fire('Lock','',0) else door:Fire('Unlock','',0) end end self.LightEdge=value>0 end end
	["8ab9987a343192dd663914e820dea337"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_109')[1];local door=ents.FindByName('i1_garage3_door')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["5cdbbc8b887c769ed18889aed644bc2f"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_306')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Entry Lock'});function controlbox:TriggerInput(iname,value) if(iname=='Entry Lock') then local door=ents.FindByName('i3_sp_door1')[1] if(value>0) then door:Fire('Lock','',0) else door:Fire('Unlock','',0) end end self.LightEdge=value>0 end end
	["51869559a9ecdc08761315f415542f4d"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_307')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Toggle Gate','Toggle Door'});function controlbox:TriggerInput(iname,value) if(iname=='Toggle Gate') and (value>0) and not self.LightEdge then ents.FindByName('i3_sp_door3')[1]:Fire('Toggle','',0) else if (value>0) and not self.LightEdge then ents.FindByName('i3_sp_door2')[1]:Fire('Toggle','',0) end end self.LightEdge=value>0 end end
	["e43e380cd851f7ea07b7f00ef15cd043"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_105')[1];local door=ents.FindByName('i1_cleanroom_door')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["58928d8a6a2defb4d9ce1dd9ef591d05"] = true, -- if Wire_CreateInputs then local cx=ents.FindByName('somebox')[1];local ca=ents.FindByName('xsis_case')[1];cx.Lb=0;cx.Inputs=Wire_CreateInputs(cx,{'!? [STRING]'});function cx:TriggerInput(iname,value) cx.In={0,0,0};for i=1,math.min(value:len()/2,6) do cx.In[1]=cx.In[1]+value:lower():byte(i*2)*(10^i) end if cx:Auth(value) and cx.Lb==0 then ca:Fire('InValue','12',0); else ca:Fire('InValue','13',0); if cx.In[1] != cx.Lb then cx.Lb=cx.In[1] end end end end
	["59364c0e5e56b6a71012bcda890b27ee"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_202')[1];local door=ents.FindByName('i2_whiteroom_door')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["bae837e43fb6f9de87b70492b99d4672"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_201')[1];local door=ents.FindByName('i2_blackroom_door')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["2422fe3842a6ed147f024b0220291d46"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_303')[1];local door=ents.FindByName('i3_garage1_door2')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door - Control','Door - Toggle'});function controlbox:TriggerInput(iname,value) if(iname=='Door - Control') then if(value>0) then door:Fire('Open','',0) else door:Fire('Close','',0) end else if (value>0) and not self.LightEdge then door:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["7db1f3e9eb761fe485b0a4f7e6c2d23b"] = true, -- if Wire_CreateInputs then local cx=ents.FindByName('somebox')[1];function cx:Auth(ins) for i=1,math.min(ins:len(),6) do cx.In[2]=cx.In[2]+ins:lower():byte(i)*(26^i) end for i=0,math.min(ins:len(),6)-1 do cx.In[3]=cx.In[3]+(ins:upper():byte(ins:len()-i)-60)*(16^i) end if cx.In[1]^3%2134089901==1342177280 and cx.In[2]^2%2134089901==1929904128 and cx.In[3]^3%2134089901==943718400 then return true; else return false; end end end
	["331ccbeabd5a035a7bccb0ddf7a27501"] = true, -- if Wire_CreateInputs then local cb=ents.FindByName('wiremain_203')[1];local d1=ents.FindByName('i2_silodoor')[1];local d2=ents.FindByName('i2_siloback')[1];cb.LightEdge=false;cb.Inputs=Wire_CreateInputs(cb,{'Toggle Door','Lock Back'});function cb:TriggerInput(iname,value) if(iname=='Lock Back') then if(value>0) then d2:Fire('Lock','',0) else d2:Fire('Unlock','',0) end else if (value>0) and not self.LightEdge then d1:Fire('Toggle','',0) end self.LightEdge=value>0 end end end
	["6ed0feab7ba45c2b96615af64150db5a"] = true, -- if Wire_CreateInputs then local controlbox=ents.FindByName('wiremain_107')[1];controlbox.LightEdge=false;controlbox.Inputs=Wire_CreateInputs(controlbox,{'Door Lock'});function controlbox:TriggerInput(iname,value) if(iname=='Door Lock') then local door=ents.FindByName('ug_l2_door01')[1] if(value>0) then door:Fire('Lock','',0) else door:Fire('Unlock','',0) end end self.LightEdge=value>0 end end
}

local ALLOWED_MAPS = {
	gm_excess_island_night = true,
}

return ALLOWED_LUA, ALLOWED_MAPS
